#pragma once

#include "../src/Global.h"
#include "../src/Pipeline.h"
#include "../src/GraphicsGlobalData.h"
#include "../src/XRenderApp.h"
#include "../src/Cull.h"
#include "../src/Color.h"
#include "../src/Camera.h"
#include "../src/Shader.h"
#include "../src/Semantic.h"
#include "../src/Scene.h"
#include "../src/Sampler2D.h"
#include "../src/resources/Resources.h"
#include "../src/Shapes/Shape.h"
#include "../thirdParty/include/geometry.h"